# Generated by Django 5.1.2 on 2024-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
