# Generated by Django 5.1.3 on 2024-11-17 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0003_profile_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Gerente', 'Gerente | Mordomo'), ('Funcionario', 'Vilão'), ('Assistente', 'Assistente')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
