# Generated by Django 5.1.3 on 2024-11-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0004_profile_profile_image_alter_profile_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_images/'),
        ),
    ]
