# Generated by Django 5.1.3 on 2024-11-19 00:09

import sistema_de_seguranca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[sistema_de_seguranca.models.validate_image]),
        ),
    ]
