# Generated by Django 5.1.3 on 2024-11-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0007_rename_cargo_profile_cargo_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cargo_choices',
            new_name='cargo',
        ),
    ]
