# Generated by Django 5.1.3 on 2024-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0008_rename_cargo_choices_profile_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='codigo_recuperacao',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Gerente', 'Gerente'), ('Funcionario', 'Funcionário'), ('Assistente', 'Assistente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
