# Generated by Django 5.1.3 on 2024-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_seguranca', '0009_remove_profile_codigo_recuperacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
